version: '3.9'

services:
  app:
    build: .
    ports:
      - "5000:8080"
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: 5432
      DATABASE: video-drone
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=video-drone
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5

volumes:
  pgdata:
