version: '3.9'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - db-link
      - default

  database:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=video-drone
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
    networks:
      db-link:
        ipv4_address: 10.168.16.2

networks:
  db-link:
    driver: bridge
    ipam:
      config:
        - subnet: 10.168.0.0/16
          gateway: 10.168.16.1

volumes:
  pgdata:
