version: '3.8'

services:
  drone-worker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - RABBITMQ_URL_CONNECTION=amqp://admin:admin@127.0.0.1:5672/%2F
    network_mode: "host"
